//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyTSEntities : DbContext
    {
        public QuanLyTSEntities()
            : base("name=QuanLyTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblBoPhan> tblBoPhans { get; set; }
        public virtual DbSet<tblCanBoGiaoVien> tblCanBoGiaoViens { get; set; }
        public virtual DbSet<tblChiTietChuyen> tblChiTietChuyens { get; set; }
        public virtual DbSet<tblChiTietGiaoNhan> tblChiTietGiaoNhans { get; set; }
        public virtual DbSet<tblChiTietPhieuMuon> tblChiTietPhieuMuons { get; set; }
        public virtual DbSet<tblChiTietPhieuTra> tblChiTietPhieuTras { get; set; }
        public virtual DbSet<tblDonVi> tblDonVis { get; set; }
        public virtual DbSet<tblDuAn> tblDuAns { get; set; }
        public virtual DbSet<tblGroupAsset> tblGroupAssets { get; set; }
        public virtual DbSet<tblKhoLuuTru> tblKhoLuuTrus { get; set; }
        public virtual DbSet<tblKhoTaiSan> tblKhoTaiSans { get; set; }
        public virtual DbSet<tblLoaiTaiSan> tblLoaiTaiSans { get; set; }
        public virtual DbSet<tblNoiSuDung> tblNoiSuDungs { get; set; }
        public virtual DbSet<tblNoiSuDungTaiSan> tblNoiSuDungTaiSans { get; set; }
        public virtual DbSet<tblPhieuBanGiao> tblPhieuBanGiaos { get; set; }
        public virtual DbSet<tblQuaTrinhDiChuyen> tblQuaTrinhDiChuyens { get; set; }
        public virtual DbSet<tblTaiKhoan> tblTaiKhoans { get; set; }
        public virtual DbSet<tblTaiSan> tblTaiSans { get; set; }
        public virtual DbSet<tblTinhTrang> tblTinhTrangs { get; set; }
    
        public virtual ObjectResult<proThongKeThanhLy_Result> proThongKeThanhLy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proThongKeThanhLy_Result>("proThongKeThanhLy");
        }
    
        public virtual ObjectResult<FeedBack1_Result> FeedBack1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FeedBack1_Result>("FeedBack1");
        }
    
        public virtual ObjectResult<FeedBack2_Result> FeedBack2(string manguoimuon)
        {
            var manguoimuonParameter = manguoimuon != null ?
                new ObjectParameter("Manguoimuon", manguoimuon) :
                new ObjectParameter("Manguoimuon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FeedBack2_Result>("FeedBack2", manguoimuonParameter);
        }
    
        public virtual ObjectResult<Loadgriddieuchuyen_Result> Loadgriddieuchuyen(string manguoimuon)
        {
            var manguoimuonParameter = manguoimuon != null ?
                new ObjectParameter("Manguoimuon", manguoimuon) :
                new ObjectParameter("Manguoimuon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Loadgriddieuchuyen_Result>("Loadgriddieuchuyen", manguoimuonParameter);
        }
    
        public virtual int proSuaBienBanBanGiao(string maBienBan, string donViGiaoID, string maCBGVNhan, Nullable<System.DateTime> ngayGiao)
        {
            var maBienBanParameter = maBienBan != null ?
                new ObjectParameter("MaBienBan", maBienBan) :
                new ObjectParameter("MaBienBan", typeof(string));
    
            var donViGiaoIDParameter = donViGiaoID != null ?
                new ObjectParameter("DonViGiaoID", donViGiaoID) :
                new ObjectParameter("DonViGiaoID", typeof(string));
    
            var maCBGVNhanParameter = maCBGVNhan != null ?
                new ObjectParameter("MaCBGVNhan", maCBGVNhan) :
                new ObjectParameter("MaCBGVNhan", typeof(string));
    
            var ngayGiaoParameter = ngayGiao.HasValue ?
                new ObjectParameter("NgayGiao", ngayGiao) :
                new ObjectParameter("NgayGiao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proSuaBienBanBanGiao", maBienBanParameter, donViGiaoIDParameter, maCBGVNhanParameter, ngayGiaoParameter);
        }
    
        public virtual int proSuaLoaiTaiSan(string maLoai, string tenLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proSuaLoaiTaiSan", maLoaiParameter, tenLoaiParameter);
        }
    
        public virtual int proSuaTaiSan(string maTaiSan, string maLoai, string tenTaiSan, string thongSoKyThuat, Nullable<int> namSD, string xuatXu, string thoiGianBaoHanh, string donViTinh, string ghiChu)
        {
            var maTaiSanParameter = maTaiSan != null ?
                new ObjectParameter("MaTaiSan", maTaiSan) :
                new ObjectParameter("MaTaiSan", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenTaiSanParameter = tenTaiSan != null ?
                new ObjectParameter("TenTaiSan", tenTaiSan) :
                new ObjectParameter("TenTaiSan", typeof(string));
    
            var thongSoKyThuatParameter = thongSoKyThuat != null ?
                new ObjectParameter("ThongSoKyThuat", thongSoKyThuat) :
                new ObjectParameter("ThongSoKyThuat", typeof(string));
    
            var namSDParameter = namSD.HasValue ?
                new ObjectParameter("NamSD", namSD) :
                new ObjectParameter("NamSD", typeof(int));
    
            var xuatXuParameter = xuatXu != null ?
                new ObjectParameter("XuatXu", xuatXu) :
                new ObjectParameter("XuatXu", typeof(string));
    
            var thoiGianBaoHanhParameter = thoiGianBaoHanh != null ?
                new ObjectParameter("ThoiGianBaoHanh", thoiGianBaoHanh) :
                new ObjectParameter("ThoiGianBaoHanh", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proSuaTaiSan", maTaiSanParameter, maLoaiParameter, tenTaiSanParameter, thongSoKyThuatParameter, namSDParameter, xuatXuParameter, thoiGianBaoHanhParameter, donViTinhParameter, ghiChuParameter);
        }
    
        public virtual int proThemBienBanBanGiao(string maBienBan, string donViGiaoID, string maCBGVNhan, Nullable<System.DateTime> ngayGiao)
        {
            var maBienBanParameter = maBienBan != null ?
                new ObjectParameter("MaBienBan", maBienBan) :
                new ObjectParameter("MaBienBan", typeof(string));
    
            var donViGiaoIDParameter = donViGiaoID != null ?
                new ObjectParameter("DonViGiaoID", donViGiaoID) :
                new ObjectParameter("DonViGiaoID", typeof(string));
    
            var maCBGVNhanParameter = maCBGVNhan != null ?
                new ObjectParameter("MaCBGVNhan", maCBGVNhan) :
                new ObjectParameter("MaCBGVNhan", typeof(string));
    
            var ngayGiaoParameter = ngayGiao.HasValue ?
                new ObjectParameter("NgayGiao", ngayGiao) :
                new ObjectParameter("NgayGiao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proThemBienBanBanGiao", maBienBanParameter, donViGiaoIDParameter, maCBGVNhanParameter, ngayGiaoParameter);
        }
    
        public virtual int proThemLoaiTS(string maLoai, string tenLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proThemLoaiTS", maLoaiParameter, tenLoaiParameter);
        }
    
        public virtual int proThemTaiSan(string maTaiSan, string maLoai, string tenTaiSan, string thongSoKyThuat, Nullable<int> namSD, string xuatXu, string thoiGianBaoHanh, string donViTinh, string ghiChu)
        {
            var maTaiSanParameter = maTaiSan != null ?
                new ObjectParameter("MaTaiSan", maTaiSan) :
                new ObjectParameter("MaTaiSan", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenTaiSanParameter = tenTaiSan != null ?
                new ObjectParameter("TenTaiSan", tenTaiSan) :
                new ObjectParameter("TenTaiSan", typeof(string));
    
            var thongSoKyThuatParameter = thongSoKyThuat != null ?
                new ObjectParameter("ThongSoKyThuat", thongSoKyThuat) :
                new ObjectParameter("ThongSoKyThuat", typeof(string));
    
            var namSDParameter = namSD.HasValue ?
                new ObjectParameter("NamSD", namSD) :
                new ObjectParameter("NamSD", typeof(int));
    
            var xuatXuParameter = xuatXu != null ?
                new ObjectParameter("XuatXu", xuatXu) :
                new ObjectParameter("XuatXu", typeof(string));
    
            var thoiGianBaoHanhParameter = thoiGianBaoHanh != null ?
                new ObjectParameter("ThoiGianBaoHanh", thoiGianBaoHanh) :
                new ObjectParameter("ThoiGianBaoHanh", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proThemTaiSan", maTaiSanParameter, maLoaiParameter, tenTaiSanParameter, thongSoKyThuatParameter, namSDParameter, xuatXuParameter, thoiGianBaoHanhParameter, donViTinhParameter, ghiChuParameter);
        }
    
        public virtual int proThemTinhTrangTS(string moTaTinhTrang, string ghiChu)
        {
            var moTaTinhTrangParameter = moTaTinhTrang != null ?
                new ObjectParameter("MoTaTinhTrang", moTaTinhTrang) :
                new ObjectParameter("MoTaTinhTrang", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proThemTinhTrangTS", moTaTinhTrangParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<proThongKeCongCuVatTu_Result> proThongKeCongCuVatTu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proThongKeCongCuVatTu_Result>("proThongKeCongCuVatTu");
        }
    
        public virtual ObjectResult<proThongKeTaiSanCoDinh_Result> proThongKeTaiSanCoDinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proThongKeTaiSanCoDinh_Result>("proThongKeTaiSanCoDinh");
        }
    
        public virtual ObjectResult<proTimKiemTaiSanTheoNoiSuDung_Result> proTimKiemTaiSanTheoNoiSuDung(string tenTaiSan, string maNoiSD)
        {
            var tenTaiSanParameter = tenTaiSan != null ?
                new ObjectParameter("TenTaiSan", tenTaiSan) :
                new ObjectParameter("TenTaiSan", typeof(string));
    
            var maNoiSDParameter = maNoiSD != null ?
                new ObjectParameter("MaNoiSD", maNoiSD) :
                new ObjectParameter("MaNoiSD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proTimKiemTaiSanTheoNoiSuDung_Result>("proTimKiemTaiSanTheoNoiSuDung", tenTaiSanParameter, maNoiSDParameter);
        }
    
        public virtual ObjectResult<proTimKiemTaiSanTrongKho_Result> proTimKiemTaiSanTrongKho(string tenTaiSan, string maKho)
        {
            var tenTaiSanParameter = tenTaiSan != null ?
                new ObjectParameter("TenTaiSan", tenTaiSan) :
                new ObjectParameter("TenTaiSan", typeof(string));
    
            var maKhoParameter = maKho != null ?
                new ObjectParameter("MaKho", maKho) :
                new ObjectParameter("MaKho", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proTimKiemTaiSanTrongKho_Result>("proTimKiemTaiSanTrongKho", tenTaiSanParameter, maKhoParameter);
        }
    
        public virtual int proXoaBienBanBanGiao(string maBienBan)
        {
            var maBienBanParameter = maBienBan != null ?
                new ObjectParameter("MaBienBan", maBienBan) :
                new ObjectParameter("MaBienBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proXoaBienBanBanGiao", maBienBanParameter);
        }
    
        public virtual int proXoaLoaiTS(string maLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proXoaLoaiTS", maLoaiParameter);
        }
    
        public virtual int proXoaTaiSan(string maTaiSan)
        {
            var maTaiSanParameter = maTaiSan != null ?
                new ObjectParameter("MaTaiSan", maTaiSan) :
                new ObjectParameter("MaTaiSan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proXoaTaiSan", maTaiSanParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<st_LayBoPhan_Result> st_LayBoPhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayBoPhan_Result>("st_LayBoPhan");
        }
    
        public virtual ObjectResult<st_LayMaGiaoVien_Result> st_LayMaGiaoVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMaGiaoVien_Result>("st_LayMaGiaoVien");
        }
    
        public virtual ObjectResult<st_LayMakho1_Result> st_LayMakho1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMakho1_Result>("st_LayMakho1");
        }
    
        public virtual ObjectResult<st_LayMaNoiSD_Result> st_LayMaNoiSD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMaNoiSD_Result>("st_LayMaNoiSD");
        }
    
        public virtual int st_LayMaPhieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_LayMaPhieu");
        }
    
        public virtual int st_LayMaPhieuTra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_LayMaPhieuTra");
        }
    
        public virtual ObjectResult<st_LayMaTaiSan_Result> st_LayMaTaiSan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMaTaiSan_Result>("st_LayMaTaiSan");
        }
    
        public virtual ObjectResult<st_LayMaTaiSandieuchuyen_Result> st_LayMaTaiSandieuchuyen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMaTaiSandieuchuyen_Result>("st_LayMaTaiSandieuchuyen");
        }
    
        public virtual ObjectResult<st_LayMaTaiSanTra_Result> st_LayMaTaiSanTra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMaTaiSanTra_Result>("st_LayMaTaiSanTra");
        }
    
        public virtual ObjectResult<st_LayMayChieu_Result> st_LayMayChieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMayChieu_Result>("st_LayMayChieu");
        }
    
        public virtual int st_LayMayChieu1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_LayMayChieu1");
        }
    
        public virtual ObjectResult<st_LayMayChieu2_Result> st_LayMayChieu2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMayChieu2_Result>("st_LayMayChieu2");
        }
    
        public virtual ObjectResult<st_LayMayChieuTra_Result> st_LayMayChieuTra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayMayChieuTra_Result>("st_LayMayChieuTra");
        }
    
        public virtual ObjectResult<st_LayThanhvien_Result> st_LayThanhvien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_LayThanhvien_Result>("st_LayThanhvien");
        }
    
        public virtual ObjectResult<st_Loadgridmataisandieuchuyen_Result> st_Loadgridmataisandieuchuyen(string manguoichuyen)
        {
            var manguoichuyenParameter = manguoichuyen != null ?
                new ObjectParameter("Manguoichuyen", manguoichuyen) :
                new ObjectParameter("Manguoichuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_Loadgridmataisandieuchuyen_Result>("st_Loadgridmataisandieuchuyen", manguoichuyenParameter);
        }
    
        public virtual ObjectResult<st_Loadgridmataisanmuon_Result> st_Loadgridmataisanmuon(string manguoimuon)
        {
            var manguoimuonParameter = manguoimuon != null ?
                new ObjectParameter("Manguoimuon", manguoimuon) :
                new ObjectParameter("Manguoimuon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_Loadgridmataisanmuon_Result>("st_Loadgridmataisanmuon", manguoimuonParameter);
        }
    
        public virtual ObjectResult<st_Loadgridmataisantra_Result> st_Loadgridmataisantra(string manguoitra)
        {
            var manguoitraParameter = manguoitra != null ?
                new ObjectParameter("Manguoitra", manguoitra) :
                new ObjectParameter("Manguoitra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_Loadgridmataisantra_Result>("st_Loadgridmataisantra", manguoitraParameter);
        }
    
        public virtual ObjectResult<st_Loadgridmaychieu_Result> st_Loadgridmaychieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_Loadgridmaychieu_Result>("st_Loadgridmaychieu");
        }
    
        public virtual ObjectResult<st_QuenMatKhau_Result> st_QuenMatKhau(string tenDN, string email)
        {
            var tenDNParameter = tenDN != null ?
                new ObjectParameter("tenDN", tenDN) :
                new ObjectParameter("tenDN", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_QuenMatKhau_Result>("st_QuenMatKhau", tenDNParameter, emailParameter);
        }
    
        public virtual ObjectResult<st_TraMayChieu_Result> st_TraMayChieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_TraMayChieu_Result>("st_TraMayChieu");
        }
    
        public virtual ObjectResult<thongke1_Result> thongke1(string manguoimuon)
        {
            var manguoimuonParameter = manguoimuon != null ?
                new ObjectParameter("Manguoimuon", manguoimuon) :
                new ObjectParameter("Manguoimuon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke1_Result>("thongke1", manguoimuonParameter);
        }
    
        public virtual ObjectResult<thongke2_Result> thongke2(string manguoimuon)
        {
            var manguoimuonParameter = manguoimuon != null ?
                new ObjectParameter("Manguoimuon", manguoimuon) :
                new ObjectParameter("Manguoimuon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke2_Result>("thongke2", manguoimuonParameter);
        }
    
        public virtual ObjectResult<thongke3_Result> thongke3(string manoisudung)
        {
            var manoisudungParameter = manoisudung != null ?
                new ObjectParameter("Manoisudung", manoisudung) :
                new ObjectParameter("Manoisudung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke3_Result>("thongke3", manoisudungParameter);
        }
    
        public virtual ObjectResult<thongke4_Result> thongke4(string manoisudung)
        {
            var manoisudungParameter = manoisudung != null ?
                new ObjectParameter("Manoisudung", manoisudung) :
                new ObjectParameter("Manoisudung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke4_Result>("thongke4", manoisudungParameter);
        }
    
        public virtual ObjectResult<thongkedieuchuyen_Result> thongkedieuchuyen(string manoisudung)
        {
            var manoisudungParameter = manoisudung != null ?
                new ObjectParameter("Manoisudung", manoisudung) :
                new ObjectParameter("Manoisudung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkedieuchuyen_Result>("thongkedieuchuyen", manoisudungParameter);
        }
    
        public virtual ObjectResult<thongketaisanchotra_Result> thongketaisanchotra(string manguoimuon)
        {
            var manguoimuonParameter = manguoimuon != null ?
                new ObjectParameter("Manguoimuon", manguoimuon) :
                new ObjectParameter("Manguoimuon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongketaisanchotra_Result>("thongketaisanchotra", manguoimuonParameter);
        }
    
        public virtual ObjectResult<thongketaisandangchomuon_Result> thongketaisandangchomuon(string manguoimuon)
        {
            var manguoimuonParameter = manguoimuon != null ?
                new ObjectParameter("Manguoimuon", manguoimuon) :
                new ObjectParameter("Manguoimuon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongketaisandangchomuon_Result>("thongketaisandangchomuon", manguoimuonParameter);
        }
    
        public virtual int Thongketaisankho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Thongketaisankho");
        }
    
        public virtual ObjectResult<Thongtincanhantaikhoan_Result> Thongtincanhantaikhoan(string tendangnhap)
        {
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Thongtincanhantaikhoan_Result>("Thongtincanhantaikhoan", tendangnhapParameter);
        }
    
        public virtual ObjectResult<timtheotentaisan_Result> timtheotentaisan(string tentaisan)
        {
            var tentaisanParameter = tentaisan != null ?
                new ObjectParameter("tentaisan", tentaisan) :
                new ObjectParameter("tentaisan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timtheotentaisan_Result>("timtheotentaisan", tentaisanParameter);
        }
    }
}
