//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietPhieuTra
    {
        public int MaPhieuTra { get; set; }
        public string MaTaiSan { get; set; }
        public string MaKho { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaNoiSD { get; set; }
        public string MaNguoiTra { get; set; }
        public string MaNguoiNhan { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TrangThai { get; set; }
    
        public virtual tblCanBoGiaoVien tblCanBoGiaoVien { get; set; }
        public virtual tblKhoLuuTru tblKhoLuuTru { get; set; }
        public virtual tblNoiSuDung tblNoiSuDung { get; set; }
        public virtual tblTaiSan tblTaiSan { get; set; }
        public virtual tblTinhTrang tblTinhTrang { get; set; }
    }
}
