//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCanBoGiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCanBoGiaoVien()
        {
            this.tblChiTietPhieuMuons = new HashSet<tblChiTietPhieuMuon>();
            this.tblChiTietPhieuTras = new HashSet<tblChiTietPhieuTra>();
            this.tblPhieuBanGiaos = new HashSet<tblPhieuBanGiao>();
            this.tblQuaTrinhDiChuyens = new HashSet<tblQuaTrinhDiChuyen>();
            this.tblTaiKhoans = new HashSet<tblTaiKhoan>();
        }
    
        public string MaGiaoVien { get; set; }
        public string HoTen { get; set; }
        public string EMail { get; set; }
        public string SoDienThoai { get; set; }
        public string MaBoPhan { get; set; }
        public string QueQuan { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string TrinhDo { get; set; }
        public string ChucVu { get; set; }
        public string ChuyenMon { get; set; }
    
        public virtual tblBoPhan tblBoPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuMuon> tblChiTietPhieuMuons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuTra> tblChiTietPhieuTras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieuBanGiao> tblPhieuBanGiaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuaTrinhDiChuyen> tblQuaTrinhDiChuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaiKhoan> tblTaiKhoans { get; set; }
    }
}
