//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietGiaoNhan
    {
        public string MaPhieuGiao { get; set; }
        public string MaTaiSan { get; set; }
        public Nullable<double> TyLeKhauHao { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string MaKho { get; set; }
        public Nullable<double> DonGiaKhauHao { get; set; }
        public Nullable<System.DateTime> NgayThangSD { get; set; }
    
        public virtual tblKhoLuuTru tblKhoLuuTru { get; set; }
        public virtual tblPhieuBanGiao tblPhieuBanGiao { get; set; }
        public virtual tblTinhTrang tblTinhTrang { get; set; }
    }
}
