//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblGroupAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGroupAsset()
        {
            this.tblLoaiTaiSans = new HashSet<tblLoaiTaiSan>();
        }
        [Required(ErrorMessage = "Mời nhập mã nhóm tài sản")]
        public string GroupAssetId { get; set; }

        [Required(ErrorMessage = "Mời nhập tên nhóm tài sản")]
        public string Name { get; set; }
        public string Descriptions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoaiTaiSan> tblLoaiTaiSans { get; set; }
    }
}
