//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblLoaiTaiSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoaiTaiSan()
        {
            this.tblTaiSans = new HashSet<tblTaiSan>();
        }

        [Required(ErrorMessage = "Mời nhập loại tài sản")]
        public string MaLoai { get; set; }
        public string TenLoai { get; set; }

        [Required(ErrorMessage = "Mời chọn nhóm tài sản")]
        public string GroupAssetId { get; set; }
        public Nullable<int> Expiry { get; set; }
    
        public virtual tblGroupAsset tblGroupAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaiSan> tblTaiSans { get; set; }
    }
}
