//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhieuBanGiao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhieuBanGiao()
        {
            this.tblChiTietGiaoNhans = new HashSet<tblChiTietGiaoNhan>();
        }
    
        public string MaPhieuGiao { get; set; }
        public string MaDonVi { get; set; }
        public string MaGiaoVien { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string TenPhieuGiao { get; set; }
    
        public virtual tblCanBoGiaoVien tblCanBoGiaoVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietGiaoNhan> tblChiTietGiaoNhans { get; set; }
        public virtual tblDonVi tblDonVi { get; set; }
    }
}
