//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuaTrinhDiChuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuaTrinhDiChuyen()
        {
            this.tblChiTietChuyens = new HashSet<tblChiTietChuyen>();
        }
    
        public string MaLanChuyen { get; set; }
        public Nullable<System.DateTime> NgayChuyen { get; set; }
        public string MaNguoiDieuChuyen { get; set; }
        public string GhiChu { get; set; }
        public string TenLanChuyen { get; set; }
    
        public virtual tblCanBoGiaoVien tblCanBoGiaoVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietChuyen> tblChiTietChuyens { get; set; }
    }
}
