//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblTaiSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTaiSan()
        {
            this.tblChiTietChuyens = new HashSet<tblChiTietChuyen>();
            this.tblChiTietPhieuMuons = new HashSet<tblChiTietPhieuMuon>();
            this.tblChiTietPhieuTras = new HashSet<tblChiTietPhieuTra>();
            this.tblKhoTaiSans = new HashSet<tblKhoTaiSan>();
            this.tblNoiSuDungTaiSans = new HashSet<tblNoiSuDungTaiSan>();
        }

        [Required(ErrorMessage = "Mời nhập mã tài sản")]
        public string MaTaiSan { get; set; }

        [Required(ErrorMessage = "Mời nhập loại tài sản")]
        public string MaLoai { get; set; }

        [Required(ErrorMessage = "Mời nhập loại tài sản")]
        public string TenTaiSan { get; set; }
        public string ThongSoKyThuat { get; set; }
        public Nullable<int> NamSX { get; set; }
        public string XuatXu { get; set; }
        public string ThoiGianBaoHanh { get; set; }
        public string DonViTinh { get; set; }
        public string GhiChu { get; set; }
        public string SerialNumber
        {
            get; set;
        }
        
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayMua { get; set; }
        public Nullable<int> MaDuAn { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int Soluong { get; set; }
        public string MaDonVi { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayBanGiao { get; set; }
        public double NguyenGia { get; set; }
        public byte[] Image { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayDuKien { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayBaoDuong { get; set; }
        public string LoaiBaoDuong { get; set; }
        public Nullable<double> SoTien { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietChuyen> tblChiTietChuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuMuon> tblChiTietPhieuMuons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuTra> tblChiTietPhieuTras { get; set; }
        public virtual tblDonVi tblDonVi { get; set; }
        public virtual tblDuAn tblDuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKhoTaiSan> tblKhoTaiSans { get; set; }
        public virtual tblLoaiTaiSan tblLoaiTaiSan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNoiSuDungTaiSan> tblNoiSuDungTaiSans { get; set; }
        public virtual tblTinhTrang tblTinhTrang { get; set; }

        public List<tblTaiSan> ListAssets_Grid { get; set; }
        public System.Web.Mvc.SelectList ListGroupAssets { get; set; }
        public string GroupAssetId { get; set; }
    }
}
