//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaiKhoan
    {
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string MaGiaoVien { get; set; }
        public string Quyen { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual tblCanBoGiaoVien tblCanBoGiaoVien { get; set; }
    }
}
